//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBankClient.BankingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogInResponse", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "sponse")]
    [System.SerializableAttribute()]
    public partial class LogInResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DepositData", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "quest")]
    [System.SerializableAttribute()]
    public partial class DepositData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationTitle {
            get {
                return this.OperationTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationTitleField, value) != true)) {
                    this.OperationTitleField = value;
                    this.RaisePropertyChanged("OperationTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResponse", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "sponse")]
    [System.SerializableAttribute()]
    public partial class PaymentResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfBankClient.BankingService.ResponseStatus ResponseStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfBankClient.BankingService.ResponseStatus ResponseStatus {
            get {
                return this.ResponseStatusField;
            }
            set {
                if ((this.ResponseStatusField.Equals(value) != true)) {
                    this.ResponseStatusField = value;
                    this.RaisePropertyChanged("ResponseStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "sponse")]
    public enum ResponseStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IncorrectLoginOrPassword = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InsufficientFunds = -11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccountNumberDoesntExist = -21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongAccountNumber = -22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OtherBankAccount = -23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AccessDenied = -41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InterbankTransferFailed = -61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankNotExists = -62,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WithdrawData", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "quest")]
    [System.SerializableAttribute()]
    public partial class WithdrawData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccessTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccessToken {
            get {
                return this.AccessTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AccessTokenField, value) != true)) {
                    this.AccessTokenField = value;
                    this.RaisePropertyChanged("AccessToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationTitle {
            get {
                return this.OperationTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationTitleField, value) != true)) {
                    this.OperationTitleField = value;
                    this.RaisePropertyChanged("OperationTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferData", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "quest")]
    [System.SerializableAttribute()]
    public partial class TransferData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiver_accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sender_accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiver_account {
            get {
                return this.receiver_accountField;
            }
            set {
                if ((object.ReferenceEquals(this.receiver_accountField, value) != true)) {
                    this.receiver_accountField = value;
                    this.RaisePropertyChanged("receiver_account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sender_account {
            get {
                return this.sender_accountField;
            }
            set {
                if ((object.ReferenceEquals(this.sender_accountField, value) != true)) {
                    this.sender_accountField = value;
                    this.RaisePropertyChanged("sender_account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationHistoryResponse", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.Service.DataContract.Re" +
        "sponse")]
    [System.SerializableAttribute()]
    public partial class OperationHistoryResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WpfBankClient.BankingService.OperationRecord[] OperationRecordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WpfBankClient.BankingService.OperationRecord[] OperationRecords {
            get {
                return this.OperationRecordsField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationRecordsField, value) != true)) {
                    this.OperationRecordsField = value;
                    this.RaisePropertyChanged("OperationRecords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationRecord", Namespace="http://schemas.datacontract.org/2004/07/WcfBankingService.operation")]
    [System.SerializableAttribute()]
    public partial class OperationRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BalanceAfterOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DebetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BalanceAfterOperation {
            get {
                return this.BalanceAfterOperationField;
            }
            set {
                if ((this.BalanceAfterOperationField.Equals(value) != true)) {
                    this.BalanceAfterOperationField = value;
                    this.RaisePropertyChanged("BalanceAfterOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Debet {
            get {
                return this.DebetField;
            }
            set {
                if ((this.DebetField.Equals(value) != true)) {
                    this.DebetField = value;
                    this.RaisePropertyChanged("Debet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankingService.IBankingService")]
    public interface IBankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/SignIn", ReplyAction="http://tempuri.org/IBankingService/SignInResponse")]
        WpfBankClient.BankingService.LogInResponse SignIn(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/SignIn", ReplyAction="http://tempuri.org/IBankingService/SignInResponse")]
        System.Threading.Tasks.Task<WpfBankClient.BankingService.LogInResponse> SignInAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Deposit", ReplyAction="http://tempuri.org/IBankingService/DepositResponse")]
        WpfBankClient.BankingService.PaymentResponse Deposit(WpfBankClient.BankingService.DepositData paymentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Deposit", ReplyAction="http://tempuri.org/IBankingService/DepositResponse")]
        System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> DepositAsync(WpfBankClient.BankingService.DepositData paymentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Withdraw", ReplyAction="http://tempuri.org/IBankingService/WithdrawResponse")]
        WpfBankClient.BankingService.PaymentResponse Withdraw(WpfBankClient.BankingService.WithdrawData paymentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Withdraw", ReplyAction="http://tempuri.org/IBankingService/WithdrawResponse")]
        System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> WithdrawAsync(WpfBankClient.BankingService.WithdrawData paymentData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Transfer", ReplyAction="http://tempuri.org/IBankingService/TransferResponse")]
        WpfBankClient.BankingService.PaymentResponse Transfer(WpfBankClient.BankingService.TransferData transferData, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/Transfer", ReplyAction="http://tempuri.org/IBankingService/TransferResponse")]
        System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> TransferAsync(WpfBankClient.BankingService.TransferData transferData, string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/GetOperationHistory", ReplyAction="http://tempuri.org/IBankingService/GetOperationHistoryResponse")]
        WpfBankClient.BankingService.OperationHistoryResponse GetOperationHistory(string accessToken, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/GetOperationHistory", ReplyAction="http://tempuri.org/IBankingService/GetOperationHistoryResponse")]
        System.Threading.Tasks.Task<WpfBankClient.BankingService.OperationHistoryResponse> GetOperationHistoryAsync(string accessToken, string accountNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingServiceChannel : WpfBankClient.BankingService.IBankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingServiceClient : System.ServiceModel.ClientBase<WpfBankClient.BankingService.IBankingService>, WpfBankClient.BankingService.IBankingService {
        
        public BankingServiceClient() {
        }
        
        public BankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfBankClient.BankingService.LogInResponse SignIn(string login, string password) {
            return base.Channel.SignIn(login, password);
        }
        
        public System.Threading.Tasks.Task<WpfBankClient.BankingService.LogInResponse> SignInAsync(string login, string password) {
            return base.Channel.SignInAsync(login, password);
        }
        
        public WpfBankClient.BankingService.PaymentResponse Deposit(WpfBankClient.BankingService.DepositData paymentData) {
            return base.Channel.Deposit(paymentData);
        }
        
        public System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> DepositAsync(WpfBankClient.BankingService.DepositData paymentData) {
            return base.Channel.DepositAsync(paymentData);
        }
        
        public WpfBankClient.BankingService.PaymentResponse Withdraw(WpfBankClient.BankingService.WithdrawData paymentData) {
            return base.Channel.Withdraw(paymentData);
        }
        
        public System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> WithdrawAsync(WpfBankClient.BankingService.WithdrawData paymentData) {
            return base.Channel.WithdrawAsync(paymentData);
        }
        
        public WpfBankClient.BankingService.PaymentResponse Transfer(WpfBankClient.BankingService.TransferData transferData, string accessToken) {
            return base.Channel.Transfer(transferData, accessToken);
        }
        
        public System.Threading.Tasks.Task<WpfBankClient.BankingService.PaymentResponse> TransferAsync(WpfBankClient.BankingService.TransferData transferData, string accessToken) {
            return base.Channel.TransferAsync(transferData, accessToken);
        }
        
        public WpfBankClient.BankingService.OperationHistoryResponse GetOperationHistory(string accessToken, string accountNumber) {
            return base.Channel.GetOperationHistory(accessToken, accountNumber);
        }
        
        public System.Threading.Tasks.Task<WpfBankClient.BankingService.OperationHistoryResponse> GetOperationHistoryAsync(string accessToken, string accountNumber) {
            return base.Channel.GetOperationHistoryAsync(accessToken, accountNumber);
        }
    }
}
